#ifndef STAB_LOG_HH
#define STAB_LOG_HH

#include "soil/Log.hh"

#define STAB_LOG_INIT(x) SOIL_LOG_INIT(x)

#define STAB_TRACE SOIL_TRACE
#define STAB_DEBUG SOIL_DEBUG
#define STAB_INFO  SOIL_INFO
#define STAB_WARNING SOIL_WARNING
#define STAB_ERROR SOIL_ERROR
#define STAB_FATAL SOIL_FATAL
#define STAB_PDU SOIL_PDU
#define STAB_CUSTOM SOIL_CUSTOM


#endif
